### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mjablecnik** [shahrushabh/Attendance#1]
Hello I am finding some easy attendance system for my purpose.
I would like try this, but you don't have any instructions for installation here.. :(
Can you please supply it?? 
Thanks

**Comment by shahrushabh** [comment]
Hi! Apologies for late reply.

I appreciate your interest in our Attendance application. Unfortunately, development for this application has been discontinued and thus it is no longer applicable for use.
If you wish to, you may explore the code base.

Thanks.
